name: Test Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Feeds Package Test Build
    uses: openwrt/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@main
    strategy:
      matrix:
        include:
          - arch: x86_64
            target: x86-64
