name: Test Build

on:
  push:
  pull_request:

jobs:
  build:
    uses: BKPepe/actions-shared-workflows/.github/workflows/multi-arch-test-build.yml@improveMatrixMultiArch
    with:
      filter_archs: "x86_64,arm_cortex-a15_neon-vfpv4"
